name: Build (UWP)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-uwp:
    strategy:
      matrix:
        arch: [x64, Win32]
    runs-on: windows-latest
    env:
      VisualStudioVersion: '16.0'

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install ROS2 dependencies
      run: |
        python -m pip install -U setuptools pip
        pip install -U vcstool
        pip install -U colcon-common-extensions
        pip install -U catkin_pkg EmPy lark-parser pyparsing pyyaml numpy
        pip install -U pytest coverage mock
        pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8 pydocstyle
        choco install -y cppcheck

    - name: Checkout ament source
      run: |
        md \dev\ament\src
        cd \dev\ament
        copy ${{github.workspace}}\ament_dotnet_uwp.repos .
        vcs import src < ament_dotnet_uwp.repos
        vcs branch
      shell: cmd

    - name: Build ament source
      run: |
        cd \dev\ament
        colcon build --event-handlers console_cohesion+ console_package_list+ --merge-install --cmake-args -A x64
      shell: cmd

    - name: Checkout ROS2 source
      run: |
        md \dev\ros2\src
        cd \dev\ros2
        copy ${{github.workspace}}\ros2_dotnet_uwp.repos .
        vcs import src < ros2_dotnet_uwp.repos
        rd /s /q src\ros2_dotnet\ros2_dotnet
        xcopy /e /i ${{github.workspace}} src\ros2_dotnet\ros2_dotnet
        vcs branch
      shell: cmd

    - name: Build ROS2 for UWP (${{ matrix.arch }})
      env:
        TARGET_ARCH: ${{ matrix.arch }}
      run: |
        cd \dev\ros2
        call ..\ament\install\local_setup.bat
        colcon build --event-handlers console_cohesion+ console_package_list+ --merge-install --packages-ignore rmw_fastrtps_dynamic_cpp rcl_logging_log4cxx rcl_logging_spdlog ros2trace tracetools_launch tracetools_read tracetools_test tracetools_trace --cmake-args -A %TARGET_ARCH% -DBUILD_TESTING=OFF -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0.18362 -DTHIRDPARTY=ON -DINSTALL_EXAMPLES=OFF -DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop
      shell: cmd

    - name: Compress ROS2 install directory
      run: |
        Compress-Archive -Path \dev\ros2\install ros2.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ros2-uwp-${{ matrix.arch }}
        path: ros2.zip


